apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
    name: {{ .Release.Name }}-talos-backup-etcd
    namespace: {{ .Release.Namespace }}
    labels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/managed-by: Helm
spec:
    roles:
        - os:etcd:backup