apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbot-ui.name" . }}
  labels:
    {{- include "chatbot-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatbot-ui.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatbot-ui.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ if .Values.image.imageSha }}{{ .Values.image.imageSha }}{{ else }}{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          ports:
            - name: {{ .Values.container.port.name }}
              containerPort: {{ .Values.container.port.containerPort }}
          {{- range $secret := .Values.secrets }}
          {{- range $env := $secret.env }}
          {{- $env_name := index $env "name" }}
          {{- $env_value := index $env "value" }}
          env:
            - name: {{ $env_name }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "chatbot-ui.name" . }}-{{ $secret.name }}
                  key: {{ $env_name }}
          {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.port.name }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.container.port.name }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      automountServiceAccountToken: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}