# Default values for chatbot-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "x"

replicaCount: 1

image:
  repository: maderdario/chatbot-ui
  tag: latest
  imageSha: ""
  pullPolicy: IfNotPresent

service:
  name: chatbot-ui
  type: ClusterIP
  servicePortName: http
  port: 80
  targetPort: 3000
  annotations: {}
  externalTrafficPolicy: Cluster
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - host: chatbot-ui.local
      paths:
        - path: /
          port: 80
  tls:
    enabled: false
    secretName: ""
    hosts:
      - host: chatbot-ui.local
        secretName: ""

secrets:
  - name: openai
    env:
      - name: OPENAI_API_KEY
        value: "test"
      - name: OPENAI_API_HOST
        value: "test"
      - name: OPENAI_API_TYPE
        value: "test"
      - name: OPENAI_API_VERSION
        value: "test"
      - name: OPENAI_ORGANIZATION
        value: "test"
  - name: azure
    env:
      - name: AZURE_DEPLOYMENT_ID
        value: "test"
  - name: model
    env:
      - name: DEFAULT_MODEL
        value: "test"
      - name: DEFAULT_SYSTEM_PROMPT
        value: "test"
  - name: google
    env:
      - name: GOOGLE_API_KEY
        value: "test"
      - name: GOOGLE_CSE_ID
        value: "test"

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}

containerName: chatbot-ui

container:
  name: chatbot-ui
  port:
    name: http
    containerPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
