{{ if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: lobe-chat
    labels:
        app.kubernetes.io/name: {{ include "lobe-chat.name" . }}
        helm.sh/chart: {{ include "lobe-chat.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY | b64enc }}
  ACCESS_CODE: {{ .Values.secret.ACCESS_CODE | b64enc }}
{{- end}}