{{ if .Values.envFromSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.envFromSecret.name }}
    labels:
        app.kubernetes.io/name: {{ include "teslamate-api.name" . }}
        helm.sh/chart: {{ include "teslamate-api.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.envFromSecret.envs }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end}}